import { PlaceType } from "@prisma/client";

// DUMMY DATA TO SEED
type FoodPlaceDummy = [string, string, PlaceType];
export const foodPlaces: FoodPlaceDummy[] = [
  ["General Western", "Astons", "RESTAURANT"],
  ["General Western", "Jack's Place", "RESTAURANT"],
  ["General Western", "Carving Board", "RESTAURANT"],
  ["General Western", "Black Tap Sg", "RESTAURANT"],
  ["General Western", "Brio", "RESTAURANT"],
  ["General Western", "Fatboys", "RESTAURANT"],
  ["General Western", "Fatburger", "RESTAURANT"],
  ["General Western", "Arbora", "RESTAURANT"],
  ["General European", "Brotzeit", "RESTAURANT"],
  ["General Western", "Collins", "RESTAURANT"],
  ["General Western", "Meat & Chill", "RESTAURANT"],
  ["General Western", "Soek Seng 1954 bicycle cafe	", "RESTAURANT"],
  ["General Western", "Harry's bar", "RESTAURANT"],
  ["General Western", "Wooloomooloo", "RESTAURANT"],
  ["General Western", "The Assembly Ground", "RESTAURANT"],
  ["General Western", "Hans im gluck", "RESTAURANT"],
  ["General Western", "Burger & Lobster", "RESTAURANT"],
  ["General Western", "Five oars coffee roasters", "RESTAURANT"],
  ["General Western", "Mad for garlic", "RESTAURANT"],
  ["General Western", "Canopy Garden Dining", "RESTAURANT"],
  ["Zi Char", "Yakun Kaya Toast", "RESTAURANT"],
  ["Zi Char", "Lee Wee & brothers", "RESTAURANT"],
  ["Zi Char", "Toastbox", "RESTAURANT"],
  ["Zi Char", "Crave", "RESTAURANT"],
  ["Zi Char", "Dancing Crab", "RESTAURANT"],
  ["Zi Char", "Slappy Cakes", "RESTAURANT"],
  ["Zi Char", "Tunglok Singatures", "RESTAURANT"],
  ["Zi Char", "Tunglok Seafood", "RESTAURANT"],
  ["Zi Char", "Singapore Seafood Republic", "RESTAURANT"],
  ["Zi Char", "TASTE by Tunglok", "RESTAURANT"],
  ["Zi Char", "Lokkee", "RESTAURANT"],
  ["Zi Char", "Long Beach Seafood", "RESTAURANT"],
  ["Zi Char", "Jumbo seafood ", "RESTAURANT"],
  ["Zi Char", "Two Chefs Eating Place", "RESTAURANT"],
  ["Zi Char", "Penang Island Kitchen", "RESTAURANT"],
  ["Zi Char", "Sembawang White Beehoon", "RESTAURANT"],
  ["Zi Char", "Sum Kee ", "RESTAURANT"],
  ["Zi Char", "Flying Wok", "HAWKER_STALL"],
  ["Zi Char", "Zai Shun", "HAWKER_STALL"],
  ["Chicken Rice", "Tian Tian", "HAWKER_STALL"],
  ["Chicken Rice", "5 Star", "RESTAURANT"],
  ["Chicken Rice", "Wee Nam Kee", "RESTAURANT"],
  ["Chicken Rice", "Soy sauce chicken", "HAWKER_STALL"],
  ["Noodles", "Ah Heng Curry chicken mee", "HAWKER_STALL"],
  ["Noodles", "Xin Mei Xiang Zong Lor Mee", "HAWKER_STALL"],
  ["Noodles", "Duck Noodles", "HAWKER_STALL"],
  ["Noodles", "Ho Huat Hokkien Mee", "HAWKER_STALL"],
  ["Chinese", "	Din Tai Fung", "RESTAURANT"],
  ["Chinese", "Crystal Jade", "RESTAURANT"],
  ["Chinese", "Lok lok", "RESTAURANT"],
  ["Chinese", "Pioneer lamb skewers", "CANTEEN_STALL"],
  ["Chinese", "Dumpling Darlings", "RESTAURANT"],
  ["Chinese", "Tim Ho Wan", "RESTAURANT"],
  ["Chinese", "Swee Choon", "RESTAURANT"],
  ["Chinese", "Haidilao", "RESTAURANT"],
  ["Chinese", "	Lanzhou beef noodles", "RESTAURANT"],
  ["Chinese", "	Putien", "RESTAURANT"],
  ["Chinese", "	Formosa delights", "RESTAURANT"],
  ["Chinese", "	Tsui Wah", "RESTAURANT"],
  ["Chinese", "	Le Shrimp Ramen", "RESTAURANT"],
  ["Chinese", "	Beauty in a pot", "RESTAURANT"],
  ["Chinese", "Hot hideout", "RESTAURANT"],
  ["Indian", "Nasi Biryani", "HAWKER_STALL"],
  ["Indian", "Sakunthala's", "RESTAURANT"],
  ["Indian", "Biryani", "HAWKER_STALL"],
  ["Indian", "Springleaf prata place", "RESTAURANT"],
  ["Indian", "Prata Wala", "RESTAURANT"],
  ["Indian", "Casuarina Curry", "RESTAURANT"],
  ["Indian", "Little India biryani", "RESTAURANT"],
  ["Malay", "Power Nasi Lemak", "HAWKER_STALL"],
  ["Italian", "Da Palao", "RESTAURANT"],
  ["Italian", "Pasta Mania", "RESTAURANT"],
  ["General European", "Marche Movenpick", "RESTAURANT"],
  ["French", "Paris Baguette", "BAKERY"],
  ["Sushi", "Makisan", "RESTAURANT"],
  ["Sushi", "Rollie Olie", "RESTAURANT"],
  ["Sushi", "Genki Sushi", "RESTAURANT"],
  ["Sushi", "Ichiban Boshi", "RESTAURANT"],
  ["Sushi", "Itacho Sushi", "RESTAURANT"],
  ["Japanese", "Monster Curry", "RESTAURANT"],
  ["Japanese", "Tendon Kohaku", "RESTAURANT"],
  ["Japanese", "Yakinikuohji", "RESTAURANT"],
  ["Japanese", "Don Don Dokki", "RESTAURANT"],
  ["Japanese", "The White Kitchen", "RESTAURANT"],
  ["Japanese", "Tori Q", "RESTAURANT"],
  ["Japanese", "Suhsi Tei", "RESTAURANT"],
  ["Japanese", "Tanuki raw", "RESTAURANT"],
  ["Japanese", "Hakata", "RESTAURANT"],
  ["Japanese", "Waa Cow", "RESTAURANT"],
  ["Japanese", "Shabu Sai", "RESTAURANT"],
  ["Japanese", "Kiseki", "RESTAURANT"],
  ["Ramen", "Ajisen ramen", "RESTAURANT"],
  ["Ramen", "Ippudo", "RESTAURANT"],
  ["Ramen", "Ichiran", "RESTAURANT"],
  ["Ramen", "Afuri", "RESTAURANT"],
  ["Ramen", "Ramen Champion", "RESTAURANT"],
  ["Ramen", "Menbaka Fire ramen", "RESTAURANT"],
  ["Korean", "Nipong Naepong", "RESTAURANT"],
  ["Korean", "Seoul Yummy", "RESTAURANT"],
  ["Korean", "Pizzamaru", "RESTAURANT"],
  ["Kbbq", "Kcook", "RESTAURANT"],
  ["Kbbq", "Dookki", "RESTAURANT"],
  ["Kbbq", "Yoogane", "RESTAURANT"],
  ["Thai", "Nakhon kitchen", "RESTAURANT"],
  ["Thai", "Siam square mookata", "RESTAURANT"],
  ["Thai", "BKK Bistro & Bar", "RESTAURANT"],
  ["Vietnamese", "So Pho", "RESTAURANT"],
  ["Swedish", "IKEA", "RESTAURANT"],
  ["Indonesian", "Ayam Penyet Ria", "RESTAURANT"],
  ["Mexican", "Guzman Y Gomez", "RESTAURANT"],
  ["Mexican", "Taco Bell", "RESTAURANT"],
  ["Korean Dessert", "Nunsaram", "DESSERT_PLACE"],
  ["Korean Dessert", "Cafe +82", "DESSERT_PLACE"],
  [
    "Ice cream / yoghurt Desserts",
    "Birds of Paradise Gelato & Boutique",
    "DESSERT_PLACE",
  ],
  ["Ice cream / yoghurt Desserts", "An Acai Affair", "DESSERT_PLACE"],
  ["Ice cream / yoghurt Desserts", "Anderson's ice cream", "DESSERT_PLACE"],
  ["Ice cream / yoghurt Desserts", "Udder's ice cream", "DESSERT_PLACE"],
  ["Ice cream / yoghurt Desserts", "Yole", "DESSERT_PLACE"],
  ["Cakes / Pastry Desserts", "Rich and Good Cake", "DESSERT_PLACE"],
  ["Cakes / Pastry Desserts", "Lady M", "DESSERT_PLACE"],
  ["Cakes / Pastry Desserts", "Cedele", "DESSERT_PLACE"],
  ["Cakes / Pastry Desserts", "Chateraise", "DESSERT_PLACE"],
  ["Cakes / Pastry Desserts", "Egg tarts", "BAKERY"],
  ["Cakes / Pastry Desserts", "Tiramisu Hero", "DESSERT_PLACE"],
  ["Cakes / Pastry Desserts", "Tiong Bahru bakery", "BAKERY"],
  ["Cakes / Pastry Desserts", "Patisserie macaron", "BAKERY"],
  ["General Desserts", "Jide Chi dessert", "DESSERT_PLACE"],
  ["General Desserts", "Hvala", "DESSERT_PLACE"],
  ["General Desserts", "Kane Mochi", "DESSERT_PLACE"],
  ["General Desserts", "Awfully chocolate", "DESSERT_PLACE"],
  ["General Desserts", "Chewy Junior", "DESSERT_PLACE"],
];

export const cuisines = [
  "General Western",
  "General European",
  "Chinese",
  "Indian",
  "Italian",
  "Japanese",
  "Korean",
  "Malay",
  "Thai",
  "Vietnamese",
  "Indonesian",
  "Peranakan",
  "Mexican",
  "Swedish",
  "French",
  "Desserts",
];

export const placesByCuisine = [
  [1, 1],
  [2, 1],
  [3, 1],
  [4, 1],
  [5, 1],
  [6, 1],
  [7, 1],
  [8, 1],
  [9, 2],
  [10, 1],
  [11, 1],
  [12, 1],
  [13, 1],
  [14, 1],
  [15, 1],
  [16, 1],
  [17, 1],
  [18, 1],
  [19, 1],
  [20, 1],
  [21, 3],
  [22, 3],
  [23, 3],
  [24, 3],
  [25, 3],
  [26, 3],
  [27, 3],
  [28, 3],
  [29, 3],
  [30, 3],
  [31, 3],
  [32, 3],
  [33, 3],
  [34, 3],
  [35, 3],
  [36, 3],
  [37, 3],
  [38, 3],
  [39, 3],
  [40, 3],
  [41, 3],
  [42, 3],
  [43, 3],
  [44, 3],
  [45, 3],
  [46, 3],
  [47, 3],
  [48, 3],
  [49, 3],
  [50, 3],
  [51, 3],
  [52, 3],
  [53, 3],
  [54, 3],
  [55, 3],
  [56, 3],
  [57, 3],
  [58, 3],
  [59, 3],
  [60, 3],
  [61, 3],
  [62, 3],
  [63, 4],
  [64, 4],
  [65, 4],
  [66, 4],
  [67, 4],
  [68, 4],
  [69, 4],
  [70, 8],
  [71, 5],
  [72, 5],
  [73, 2],
  [74, 15],
  [75, 6],
  [76, 6],
  [77, 6],
  [78, 6],
  [79, 6],
  [80, 6],
  [81, 6],
  [82, 6],
  [83, 6],
  [84, 6],
  [85, 6],
  [86, 6],
  [87, 6],
  [88, 6],
  [89, 6],
  [90, 6],
  [91, 6],
  [92, 6],
  [93, 6],
  [94, 6],
  [95, 6],
  [96, 6],
  [97, 6],
  [98, 7],
  [99, 7],
  [100, 7],
  [101, 7],
  [102, 7],
  [103, 7],
  [104, 9],
  [105, 9],
  [106, 9],
  [107, 10],
  [108, 14],
  [109, 11],
  [110, 13],
  [111, 13],
  [112, 7],
  [113, 7],
  [114, 16],
  [115, 16],
  [116, 16],
  [117, 16],
  [118, 16],
  [119, 16],
  [120, 16],
  [121, 16],
  [122, 16],
  [123, 16],
  [124, 16],
  [125, 16],
  [126, 16],
  [127, 16],
  [128, 16],
  [129, 16],
  [130, 16],
  [131, 16],
];

export const dishes = [
  "pizza",
  "sushi",
  "ramen",
  "zi char",
  "chicken rice",
  "hokkien mee",
  "char kway teow",
  "nasi lemak",
  "roti prata",
  "nasi biryani",
  "maggie goreng",
  "dim sum",
  "japanese hotpot",
  "japanese bbq",
  "chinese hotpot",
  "kbbq",
  "korean desserts",
  "chicken chop",
];

export const placesByDish = [
  [1, 18],
  [2, 18],
  [3, 18],
  [4, 18],
  [5, 18],
  [6, 18],
  [7, 18],
  [8, 18],
  [9, 18],
  [10, 18],
  [11, 18],
  [12, 18],
  [13, 18],
  [14, 18],
  [15, 18],
  [16, 18],
  [17, 18],
  [18, 18],
  [19, 18],
  [20, 18],
  [21, 4],
  [22, 4],
  [23, 4],
  [24, 4],
  [25, 4],
  [26, 4],
  [27, 4],
  [28, 4],
  [29, 4],
  [30, 4],
  [31, 4],
  [32, 4],
  [33, 4],
  [34, 4],
  [35, 4],
  [36, 4],
  [37, 4],
  [38, 4],
  [39, 4],
  [40, 5],
  [41, 5],
  [42, 5],
  [43, 5],
  [71, 1],
  [75, 2],
  [76, 2],
  [77, 2],
  [78, 2],
  [79, 2],
  [92, 3],
  [93, 3],
  [94, 3],
  [95, 3],
  [96, 3],
  [101, 16],
  [102, 16],
  [103, 16],
];

export const categories = [
  "Cooking method",
  "Food theme",
  "Dietary requirements",
  "Food type",
  "Dessert",
  "Others",
];

type TagDummy = [string, number];
export const tags: TagDummy[] = [
  ["Grilled", 1],
  ["Steamed", 1],
  ["BBQ", 1],
  ["Fried", 1],
  ["Hotpot", 1],
  ["Wrap", 2],
  ["Rice", 2],
  ["Noodle", 2],
  ["Salad", 2],
  ["Healthy", 2],
  ["Halal", 3],
  ["No beef", 3],
  ["Vegetarian", 3],
  ["Appetiser (eg salad, soup)", 4],
  ["Main course (entrees)", 4],
  ["Sides (for sharing)", 4],
  ["Beverages", 4],
  ["Ice cream", 5],
  ["Cake", 5],
  ["Pastry", 5],
  ["On the go snacks", 6],
  ["Instant meals", 6],
  ["Cold meal", 6],
  ["Hot meal", 6],
  ["Filling", 6],
  ["Value for money", 6],
  ["buffet style", 6],
  ["Seafood", 6],
];
